# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoffeeWindow(object):
    def setupUi(self, CoffeeWindow):
        CoffeeWindow.setObjectName("CoffeeWindow")
        CoffeeWindow.resize(813, 381)
        self.centralwidget = QtWidgets.QWidget(CoffeeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        CoffeeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CoffeeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        CoffeeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CoffeeWindow)
        self.statusbar.setObjectName("statusbar")
        CoffeeWindow.setStatusBar(self.statusbar)
        self.addEditAction = QtWidgets.QAction(CoffeeWindow)
        self.addEditAction.setObjectName("addEditAction")
        self.menu.addAction(self.addEditAction)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(CoffeeWindow)
        QtCore.QMetaObject.connectSlotsByName(CoffeeWindow)

    def retranslateUi(self, CoffeeWindow):
        _translate = QtCore.QCoreApplication.translate
        CoffeeWindow.setWindowTitle(_translate("CoffeeWindow", "Кофе"))
        self.menu.setTitle(_translate("CoffeeWindow", "Запись"))
        self.addEditAction.setText(_translate("CoffeeWindow", "Добавить/изменить"))
